services:
  - docker

env:
  - REPO_NAME=shrmrf/yocto-base
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t $REPO_NAME:$TRAVIS_BRANCH .
  - docker push $REPO_NAME:$TRAVIS_BRANCH
