services:
  - docker

env:
  - REPO_NAME=shrmrf/yocto-base
script:
  - docker login -u $DOCKER_USERNAME -p '$DOCKER_PASSWORD'
  - docker build --no-cache -t $REPO_NAME:$TRAVIS_BRANCH .
  - docker push $REPO_NAME:$TRAVIS_BRANCH
